### ISSUE TITLE
Media Library rejects uploaded files if file has an uppercase extension

### ISSUE THREAD

**Issue by Pieter1024** [stephenmcd/filebrowser-safe#100]
Steps to reproduce (from Mezzanine):

- Login and go to the Media Library
- Click 'Upload'
- Choose a file with a name that ends in '.JPG' (note the uppercase)
- Try to upload it

It yields an error about allowed extensions. However, .jpg is accepted. We should accept all upper-, lower- and mixed-case versions of extensions that we allow.

As a workaround, I would like to add the uppercase extensions to EXTENSIONS, but I read there in the comments 'Lower case is important' (https://github.com/stephenmcd/filebrowser-safe/blob/master/filebrowser_safe/settings.py#L34).

What is the right way to fix this? I think we could safely accept all uppercase versions of all allowed extensions, so maybe the easiest way is to just lowercase the filename before we check the extension against the EXTENSIONS list?

**Comment by stephenmcd** [comment]
Dupe #86
