### ISSUE TITLE
Slow directory listing for aws storage

### ISSUE THREAD

**Issue by philiphoy** [stephenmcd/filebrowser-safe#101]
When there are many directories in the listing the browse page load can be slow. The root cause of this seems to be multiple calls to list directories contents, one for each directory which for aws storage entails an api call. 

Looking at the source it appears this is done to calculate a delete_total variable by checking whether the file is empty :

` elif fileobject.filetype == 'Folder' and fileobject.is_empty:
                    results_var['delete_total'] += 1`

As this variable does not seem to be used by mezzananine or elsewhere within filebrowser_safe it could perhaps be removed.  Happy to make a pull request if appropriate.

**Comment by stephenmcd** [comment]
Sounds good, thank you.

**Comment by ryneeverett** [comment]
Resolved via #102.
