### ISSUE TITLE
Thumbnails not being created for jpeg/jpg files

### ISSUE THREAD

**Issue by blitzd** [stephenmcd/filebrowser-safe#105]
I'm not able to get filebrowser_safe to generate thumbnails for jpg/jpeg files. It works fine for .png files, but jpg files always show up full size. I've seen indication that for the original filebrowser you can add a missing libjpeg-dev to solve this, but I have installed that package and still find the issue is occurring with filebrowser_safe. 

Is there any way to get thumbnails for jpg with filebrowser_safe?

Edit: A bit more information...

When I run this local I can see that a directory gets created under media/.thumbnails for the corresponding jpg, but no thumbnail ever gets created inside it. I had noticed on S3 that the directory under thumbnails doesn't exist, but that's likely because S3 doesn't seem to keep empty directories around in some cases.

**Comment by jerivas** [comment]
It's an issue with Pillow. See https://github.com/stephenmcd/mezzanine/issues/1785
