### ISSUE TITLE
0.4.7 not under releases

### ISSUE THREAD

**Issue by afs2015** [stephenmcd/filebrowser-safe#110]
I was noticing on PyPy that this project is on version 0.4.7 but under the releases or tags in this GitHub repo it only goes up to 0.4.6. If this is something we want to changed i'd be happy to do so.

**Comment by jerivas** [comment]
Yes please, that would be a welcome contribution.

**Comment by afs2015** [comment]
@jerivas: After attempting to clone the repo and push up a tag for the `0.4.7` commit I was unable to include it in a pull request. I think a contributor and/or maintainer who has the ability to add tags to this project has to do it.

Commit for 0.4.7: https://github.com/stephenmcd/filebrowser-safe/commit/ba6f96fe310387b88afb9a17ef4309cb7f987663

**Comment by jerivas** [comment]
I've added the tag. Thanks for letting us know!
