### ISSUE TITLE
Ability to use auth other than django sessions when uploading

### ISSUE THREAD

**Issue by Olorin92** [stephenmcd/filebrowser-safe#118]
As per the title, it seems that the _upload_file and the @flash_login_required decorator by extension requires you to be using Django session authentication:

user_id = session_data['_auth_user_id']

This line will fail in the flash_login_required decorator if not using Django auth, and so you won't be able to upload any files successfully.

Would it be possible to make this part of the code 'pluggable', to allow custom auths to handle the fetching of the user_id?

**Comment by Olorin92** [comment]
One recommendation could be a simple check to see if the request.user has already been set, and if it has, user the ID of that user - otherwise fall back to the session_data _auth_user_id.

**Comment by stephenmcd** [comment]
That's actually redundant since we don't use flash anymore, I've remove them in ff781dd662352d6815f4a995d4246fc713c802ab
