### ISSUE TITLE
Replace Flash upload with HTML5.

### ISSUE THREAD

**Issue by stephenmcd** [stephenmcd/filebrowser-safe#33]
https://github.com/stephenmcd/mezzanine/issues/875

**Comment by vwbusguy** [comment]
It seems this has fallen off the radar (here and the maillist thread).  Is there a strong preference for merging the django-filesystem's method?  If not, developing an ajax upload handler should be pretty simple.

**Comment by stephenmcd** [comment]
I don't know what django-filesystem's method refers to.

As was the case previously, if you're willing to work on getting rid of the Flash widget it'd be more than welcome!

**Comment by nym** [comment]
+1

**Comment by kbytesys** [comment]
Now many browser started to block the flash plugin. It's time to get rid of that and put more priority against this issue please.

**Comment by molokov** [comment]
I'm also going to add a +1 here. A colleague told me the latest OSX update for his Mac means that Flash is highly sandboxed so he can't upload anything to the website on it any more, he'll have to load up a Linux or Windows VM to do so. 

Has anyone made any progress on this, even in their own fork?

**Comment by crisbeto** [comment]
I'd be willing to give this a shot, but have you considered that the original `django-filebrowser` has moved away from Flash. Is it still necessary to support this fork?

**Comment by crisbeto** [comment]
I've submitted a fix at https://github.com/stephenmcd/filebrowser-safe/pull/54

**Comment by serialworm** [comment]
Is there any movement on this getting merged?  Would be really great to have this.  Uploadify based filebrowser is not working at all on my mac at this point.

**Comment by michalfita** [comment]
+1
