### ISSUE TITLE
FileSubmit js broken on inlines

### ISSUE THREAD

**Issue by gradel** [stephenmcd/filebrowser-safe#46]
Tried to use an inline for a model wich has a key to the page model and file fields.
This line:
https://github.com/stephenmcd/filebrowser-safe/blob/master/filebrowser_safe/static/filebrowser/js/FB_FileBrowseField.js#L4
returns as input_id
`id_foo-__prefix-__pdf`
 where it should
`id_foo-__prefix__-pdf`
due to global matching.
Quick and dirty replacement worked:
`var input_id=window.name.replace(/____/,'-').replace(/______/, '__-').split("___").join(".");`

**Comment by stephenmcd** [comment]
Could you submit a PR with the fix you've made? 

Thanks

**Comment by gradel** [comment]
Sure, will look for a more elegant solution before :)

**Comment by stephenmcd** [comment]
Awesome, thanks a lot!

**Comment by gradel** [comment]
Investigating further shows the problem has another origin ( __prefix__ does not get replaced with a real prefix), code is alright as is, closing issue and sry for the noise ;).

**Comment by nielsonsantana** [comment]
This bug was solved by this PR: https://github.com/stephenmcd/filebrowser-safe/pull/93
However, no release was published yet. 
I forked the repositories (filebrowser-safe and grappelli-safe) to use on my requirements.
Example:
-e git://github.com/nielsonsantana/grappelli-safe.git#egg=grappelli_safe
