### ISSUE TITLE
Filebrowser can't delete files on Windows

### ISSUE THREAD

**Issue by epanchee** [stephenmcd/filebrowser-safe#53]
Recently I faced with problem that filebrowser can't delete files while mezzanine is running on Windows. Media files manager showed me error "An error occurred" in the red box on the top of page when I tried to delete file.
I went deeper inside filebrowser sources and found that this error occurs because get_directory() returns uploads/ with slash on the end. I added crutch to get_directory() function 
`return dirname.replace("/","")` and now anything works fine.
I'm not sure that it's global problem maybe it caused by my side but I've never changed sources of mezzanine project before.

Here is my freeze output:
azure==0.11.1
beautifulsoup4==4.4.0
bleach==1.4.1
Cartridge==0.10.0
chardet==2.3.0
dj-database-url==0.3.0
dj-static==0.0.6
Django==1.8.3
django-contrib-comments==1.6.1
django-modeltranslation==0.10
django-registration==1.0
django-toolbelt==0.0.1
ecdsa==0.13
fab==1.4.2
Fabric==1.10.2
filebrowser-safe==0.4.0
future==0.15.0
futures==3.0.3
grappelli-safe==0.4.1
gunicorn==19.3.0
html5lib==0.999999
Mezzanine==4.0.1
oauthlib==1.0.3
paramiko==1.15.2
Pillow==2.9.0
psycopg2==2.6.1
pycrypto==2.6.1
PyPDF2==1.25.1
python-dateutil==2.4.2
pytz==2015.4
reportlab==3.2.0
requests==2.7.0
requests-oauthlib==0.5.0
six==1.9.0
static3==0.6.1
tzlocal==1.2
virtualenv==13.1.0
xhtml2pdf==0.0.6

Also I'm using Windows 10.

**Comment by anic** [comment]
i found that in views.py line 375
    if not normalized.startswith(get_directory()) or ".." in normalized:

in windows system, the "normalized " variable is in format "xxx\yyy,txt",and get_directory() returns format like "xxx/" 

so in order to fix this problem , i change the local code like this ,both uses the same normpath form:
    if not normalized.startswith(os.path.normpath(get_directory())) or ".." in normalized:

**Comment by khirstinova** [comment]
Just make sure your settings file has a "\\" in the directory.  

E.G. FILEBROWSER_DIRECTORY="uploads\\"

Although, I found this issue entirely annoying.

**Comment by alexalexyang** [comment]
Hi @khirstinova , I'm new to Django and Mezzanine. I'm running into this same problem, I think. I don't understand what your solution means. Could you explain a littl ebit more where I should place the "\" in my `settings.py` file?

**Comment by khirstinova** [comment]
The answer is "anywhere" really, but the better answer is "wherever it makes the best organizational sense.  The setting isn't required to be in any specific place in the file.  Django will consume it, filebrowser will read it.


-K


________________________________

**Comment by stephenmcd** [comment]
Should be fixed in #109
