### ISSUE TITLE
upload_file give 500 (ISE) in version 0.4.2

### ISSUE THREAD

**Issue by egut** [stephenmcd/filebrowser-safe#57]
Hi

After some digging I noticed that when building (using docker) filebrowser-safe have updated to version 0.4.2 (from 0.4.1) and it looked like a good reason. But on 0.4.2 when uploading files I get:

POST http://localhost:8000/admin/media-library/upload_file/ 500 (INTERNAL SERVER ERROR)

When uploading files (images and videos) in 0.4.1 it works just fine.

**Comment by stephenmcd** [comment]
Thanks for the report, I've just pushed 0.4.3 which fixes the issue.
