### ISSUE TITLE
Can't upload files to folders with dashes

### ISSUE THREAD

**Issue by jerivas** [stephenmcd/filebrowser-safe#61]
Hey everyone. I've been using the HTML5 uploader for a while, and I think I encountered a problem uploading files to folders with dashes in their name. To reproduce:

1. Navigate to a folder with dashes in the name in Filebrowser.
1. Open the upload widget and add something to the queue.
1. Hit upload. The widget reports a "Server error".

At this point, nothing has been uploaded to the folder in use, but a new folder has been created as a sibling of this one. The name is the same, but with the string `\u002D` instead of dashes. For example, `my-folder` will create a sibling `my\U002Dfolder` when you try to upload something. The new folder will now have the files you just uploaded.

**Comment by stephenmcd** [comment]
Thanks Ed

**Comment by jerivas** [comment]
Leaving a comment for future reference (of myself and others who need to support old releases of filebrowser-safe): The fix is: https://github.com/stephenmcd/filebrowser-safe/commit/bf074a4f04fe371bdb33c1ef4908e4ddb9987f55#diff-277957d7795fc51ddf9145e686c47fc3
