### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by vladir** [stephenmcd/filebrowser-safe#63]
I know that now Mezzanine supports Django 1.9. Could I assume that filebrowser-safe also supports Django 1.9? Thanks in advance

**Comment by stephenmcd** [comment]
Please use the mailing list.

**Comment by vladir** [comment]
Hi @stephenmcd thanks for your suggestion, I will. I would also suggest that the overview of the project keeps updated with what version of Django is supported, if possible. Thanks in advance
