### ISSUE TITLE
X-Content-Type-Options

### ISSUE THREAD

**Issue by robmoggach** [stephenmcd/filebrowser-safe#64]
I'm using HTML5 Boilerplate and the following security precaution doesn't like `uploadify.swf`:

    <IfModule mod_headers.c>
        Header set X-Content-Type-Options "nosniff"
    </IfModule>

It took me a while to find this in my local dev environment which uses apache instead of `runserver`.

Is the current release of **filebrowser** still not suitable for integration in mezzanine?

**Comment by stephenmcd** [comment]
Flash widget has since been removed in the development version.
