### ISSUE TITLE
'SELECT FILES' button not shown when http header 'X-Content-Type-Options nosniff' is set

### ISSUE THREAD

**Issue by kkzxak47** [stephenmcd/filebrowser-safe#82]
Hi all,
  I'm new to mezzanine. And I'm having problem with image upload button in the Media Library.
In Chrome 51 and Firefox 48 it's the same symptom:
![screenshot from 2016-08-08 01 01 13](https://cloud.githubusercontent.com/assets/2363326/17463877/0ce90ade-5d04-11e6-9ce3-f0b9b55e182c.png)
I can reveal a input[type=file] by clearing its style and upload a image successfully:
![screenshot from 2016-08-08 01 09 13](https://cloud.githubusercontent.com/assets/2363326/17463917/f3e274e8-5d04-11e6-9f9e-ed31088f09d6.png)

Later on I found out that the issue was caused by a http header:

> X-Content-Type-Options nosniff;

Is there a plan to replace the flash button with a html5 one?

**Comment by stephenmcd** [comment]
Try installing from this git repo - it's already been addressed.
