### ISSUE TITLE
TemplateSyntaxError at /admin/media-library/upload/

### ISSUE THREAD

**Issue by cdwaddell23** [stephenmcd/filebrowser-safe#83]
Invalid block tag on line 43: 'allowed_extensions_list', expected 'endblock'. Did you forget to register or load this tag?

Django Version: 1.10
Python Version: 2.7.10
Installed Applications:
(u'mezzanine.boot',
 u'django.contrib.auth',
 u'django.contrib.contenttypes',
 u'django.contrib.redirects',
 u'django.contrib.sessions',
 u'django.contrib.sites',
 u'django.contrib.sitemaps',
 u'django.contrib.humanize',
 u'mezzanine.conf',
 u'mezzanine.core',
 u'mezzanine.generic',
 u'mezzanine.pages',
 u'mezzanine.blog',
 u'mezzanine.forms',
 u'mezzanine.galleries',
 u'mezzanine.twitter',
 u'mezzanine.accounts',
 u'mezzanine.mobile',
 u'storages',
 u'compressor',
 u'project',
 u'member',
 u'resource',
 u'showcase',
 u'product',
 u'planner',
 u'filebrowser_safe',
 u'grappelli_safe',
 u'django.contrib.admin',
 u'django.contrib.staticfiles',
 u'django_comments')
Installed Middleware:
(u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.middleware.common.CommonMiddleware',
 u'django.middleware.csrf.CsrfViewMiddleware',
 u'django.contrib.auth.middleware.AuthenticationMiddleware',
 u'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware',
 u'django.middleware.clickjacking.XFrameOptionsMiddleware',
 u'django.middleware.security.SecurityMiddleware',
 u'mezzanine.core.request.CurrentRequestMiddleware',
 u'mezzanine.core.middleware.RedirectFallbackMiddleware',
 u'mezzanine.core.middleware.TemplateForDeviceMiddleware',
 u'mezzanine.core.middleware.TemplateForHostMiddleware',
 u'mezzanine.core.middleware.AdminLoginInterfaceSelectorMiddleware',
 u'mezzanine.core.middleware.SitePermissionMiddleware',
 u'mezzanine.pages.middleware.PageMiddleware')

Template error:
In template /opt/python/run/venv/lib/python2.7/site-packages/filebrowser_safe/templates/filebrowser/upload.html, error at line 43
   Invalid block tag on line 43: 'allowed_extensions_list', expected 'endblock'. Did you forget to register or load this tag?   33 : {% block content %}
   34 : <div id="content-main">
   35 :     <form
   36 :         action="{% url 'fb_do_upload' %}"
   37 :         method="post"
   38 :         enctype="multipart/form-data"
   39 :         id="upload-form"
   40 :         data-check-url="{% url 'fb_check' %}"
   41 :         data-replace-message="{% trans 'Do you want to replace the file' %}"
   42 :         data-redirect-when-done="{% url 'fb_browse' %}{% query_string '' 'p' %}"
   43 :         data-allowed-extensions=" {% allowed_extensions_list %} "
   44 :         data-size-limit="{{ settings_var.MAX_UPLOAD_SIZE|unlocalize }}"
   45 :         data-server-error="{% trans 'There was a server error when uploading the file.' %}"
   46 :         data-size-error="{% trans 'The file size is larger than the limit.' %}"
   47 :         data-extension-error="{% trans 'The file extension is not allowed.' %}">
   48 : 
   49 :     <div>
   50 :         <fieldset class="module aligned">
   51 :         <div class="form-row">
   52 :             <div>
   53 :                 <div class="file-input-wrapper">

Traceback:

File "/opt/python/run/venv/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  39.             response = get_response(request)

File "/opt/python/run/venv/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/opt/python/run/venv/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/opt/python/run/venv/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/opt/python/run/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/opt/python/run/venv/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "/opt/python/run/venv/lib/python2.7/site-packages/django/views/decorators/clickjacking.py" in wrapped_view
  39.         resp = view_func(*args, **kwargs)

File "/opt/python/run/venv/lib/python2.7/site-packages/filebrowser_safe/views.py" in upload
  277.         'breadcrumbs_title': _(u'Upload')

File "/opt/python/run/venv/lib/python2.7/site-packages/django/shortcuts.py" in render
  30.     content = loader.render_to_string(template_name, context, request, using=using)

File "/opt/python/run/venv/lib/python2.7/site-packages/django/template/loader.py" in render_to_string
  67.         template = get_template(template_name, using=using)

File "/opt/python/run/venv/lib/python2.7/site-packages/django/template/loader.py" in get_template
  21.             return engine.get_template(template_name)

File "/opt/python/run/venv/lib/python2.7/site-packages/django/template/backends/django.py" in get_template
  39.             return Template(self.engine.get_template(template_name), self)

File "/opt/python/run/venv/lib/python2.7/site-packages/django/template/engine.py" in get_template
  160.         template, origin = self.find_template(template_name)

File "/opt/python/run/venv/lib/python2.7/site-packages/django/template/engine.py" in find_template
  134.                         name, template_dirs=dirs, skip=skip,

File "/opt/python/run/venv/lib/python2.7/site-packages/django/template/loaders/base.py" in get_template
  44.                     contents, origin, origin.template_name, self.engine,

File "/opt/python/run/venv/lib/python2.7/site-packages/django/template/base.py" in __init__
  191.         self.nodelist = self.compile_nodelist()

File "/opt/python/run/venv/lib/python2.7/site-packages/django/template/base.py" in compile_nodelist
  233.             return parser.parse()

File "/opt/python/run/venv/lib/python2.7/site-packages/django/template/base.py" in parse
  518.                     raise self.error(token, e)

Exception Type: TemplateSyntaxError at /admin/media-library/upload/
Exception Value: Invalid block tag on line 43: 'allowed_extensions_list', expected 'endblock'. Did you forget to register or load this tag?

**Comment by stephenmcd** [comment]
Can't reproduce this, make sure you've the latest version installed.

**Comment by yomguy** [comment]
Dear @stephenmcd,

It seems that fb_tags.py included in the wheel package uploaded on pypi does NOT content the `allowed_extensions_list` function. Note that the tag.gz version is OK.

Cheers

**Comment by stephenmcd** [comment]
You're right, thanks for tracking that down. 

I've no idea how it's even possible, since I publish both at the same time from the same source. Anyway I just pushed a new version with no changes, and I've manually verified the new wheel contains the latest code.

**Comment by cdwaddell23** [comment]
I have the following versions of Django, Mezzanine and filebrowser-safe.

Django 1.10
Mezzanine 4.2
filebrowser-safe 4.4

Are there other dependent packages I should be checking versions on?

**Comment by yomguy** [comment]
Thank you so much @stephenmcd 
PR submitted to upgrade it in mezzanine ;)
