### ISSUE TITLE
TemplateSyntaxError at /admin/media-library/upload/

### ISSUE THREAD

**Issue by alex2lv** [stephenmcd/filebrowser-safe#84]
Mezzanine 4.1.0
Django 1.9.9

I have this error :
_In template /home/alex/.virtualenvs/myapp/local/lib/python2.7/site-packages/filebrowser_safe/templates/filebrowser/upload.html, error at line 43
Invalid block tag on line 43: 'allowed_extensions_list', expected 'endblock'. Did you forget to register or load this tag?_

This line **data-allowed-extensions="{% allowed_extensions_list %}"**  raise an error.

So I removed this line and then the error went away.

Have you ever encountered this problem?

**Comment by stephenmcd** [comment]
#83
