### ISSUE TITLE
FileBrowseField has many differences with Django's FileField

### ISSUE THREAD

**Issue by spookylukey** [stephenmcd/filebrowser-safe#85]
I'm filing this as a bug because Mezzanine imports and subclasses either `filebrowse_safe.fields.FileBrowseField` or `django.db.models.FileField` if it is not available. So it seems like it is expecting them to work similarly.

However, the two work very differently when you access the attribute on an instance:

* Django provides the 'field' attribute on the returned `FieldFile` objects, while `FileObject` does not.
* The `FieldFile.path` attribute is the full path on Django, `FileObject.path` is a very unhelpful synonym for `FileObject.name`.
* Django's `FieldFile` acts like an actual file, with `read()`, `close()`, `__iter__()`, `__exit__()` etc. `FileObject` does not.

This makes `FileBrowserField` a very buggy drop in replacement - if you simply install filebrowser_safe, these fields will start behaving very differently.

**Comment by ryneeverett** [comment]
Have you tried the latest release? I believe the only remaining issue is the `path` behaviour, which is deprecated and will be fixed in a future version.

**Comment by spookylukey** [comment]
My apologies - I didn't check the latest version, I should have done so before creating this issue, and the code looks different from what I'm experiencing. I'll re-open if there is still anything to address.

**Comment by ryneeverett** [comment]
No problem here. I'm glad to know somebody else values this.
