### ISSUE TITLE
HTML 5 uploader doesn't allow multiple selection of files

### ISSUE THREAD

**Issue by cjh79** [stephenmcd/filebrowser-safe#89]
Just updated to 0.4.6. The new HTML5-based file uploader pops up a file input dialog that only allows for selecting one file at a time. It would be much more useful if we could select multiple.

It seems the file input needs a "multiple" attribute, and there needs to be some additional processing in the upload.js file to handle the multiple files that come back.

If people agree that this change is needed, I would be happy to work on it so long as I'm not stepping on anyone's toes.

**Comment by stephenmcd** [comment]
Sounds like a good improvement, go for it.

**Comment by stephenmcd** [comment]
d094b8e85fefa9f61b3156530de7892eb5b8a425
